[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "echo" # need to call anchor test to update metadata field in idl before running tests, so just do a noop
lint = "yarn prettify:fix && cargo fmt"
fulltest = 'cargo test && bash ./test-scripts/run-anchor-tests.sh'
watch_ts = 'find ./programs/clearing_house/src/* ./tests ./sdk/src | entr -c bash ./test-scripts/single-anchor-test.sh'
watch_build = 'find ./programs/clearing_house/src/* ./tests ./sdk/src | entr -c anchor build'
watch_cargo = 'find ./programs/clearing_house/src/* ./tests ./sdk/src | entr -c cargo test -- --show-output'

[programs.localnet]
drift = "dRiftyHA39MWEi3m9aunc5MzRF1JYuBsbn6VPcn33UH"
pyth = "FsJ3A3u2vn5cTVofAjvy6y5kwABJAqYWpe4975bi2epH"
token_faucet = "V4v1mQiAdLz4qwckEb45WqHYceYizoib39cDBHSWfaB"