name: Deploy Typescript SDK Docs

on:
  push:
    branches: ["master", "wphan/sdk_docs_gen"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  check-for-sdk-changes:
    runs-on: ubicloud
    # Set job outputs to values from filter step
    outputs:
      sdk: ${{ steps.filter.outputs.sdk }}
    steps:
      # For pull requests it's not necessary to checkout the code
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            sdk:
              - 'sdk/**'
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}/sdk
    runs-on: ubicloud
    needs: check-for-sdk-changes
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"
      - name: Generate docs
        run: npm install && npm run generate-docs
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code docs || echo "changes=true" >> $GITHUB_OUTPUT
      - name: Commit changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add docs
          git commit -m "Update SDK documentation"
          git push origin HEAD
      - name: Setup Pages
        if: steps.git-check.outputs.changes == 'true'
        uses: actions/configure-pages@v5
      - name: Upload artifact
        if: steps.git-check.outputs.changes == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'
      - name: Deploy to GitHub Pages
        if: steps.git-check.outputs.changes == 'true'
        id: deployment
        uses: actions/deploy-pages@v4
